edition = "2021"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_try_shorthand = true
force_explicit_abi = false
use_small_heuristics = "Off"
# fn_params_layout = "Vertical"
use_field_init_shorthand = true
match_block_trailing_comma = true
max_width = 105
fn_call_width = 105
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
